# Generated by Django 5.0.3 on 2024-07-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('university', models.CharField(choices=[('SIT', 'SIT'), ('HUST', 'HUST')], max_length=4)),
                ('password', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('is_creator', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
