# Generated by Django 5.0.3 on 2024-07-27 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='User_Profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_user',
        ),
    ]
