# Generated by Django 5.0.3 on 2024-07-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='old_cart',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
