# Generated by Django 5.0.3 on 2024-07-29 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitems_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='purchased_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 29, 18, 5, 15, 846633, tzinfo=datetime.timezone.utc)),
        ),
    ]
