# Generated by Django 5.0.3 on 2024-07-30 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitems_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='purchased_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 3, 44, 31, 155111, tzinfo=datetime.timezone.utc)),
        ),
    ]
