# Generated by Django 5.0.3 on 2024-07-30 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitems_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='purchased_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 30, 8, 3, 30, 954152, tzinfo=datetime.timezone.utc)),
        ),
    ]
