# Generated by Django 5.0.3 on 2024-07-31 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_orderitems_purchased_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='purchased_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 2, 12, 11, 453995, tzinfo=datetime.timezone.utc)),
        ),
    ]
