# Generated by Django 5.0.3 on 2024-07-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='youtube_url',
        ),
    ]
