# Generated by Django 5.0.3 on 2024-07-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_courses_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='intro',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
