# Generated by Django 5.0.3 on 2024-07-29 18:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
