# Generated by Django 5.0.3 on 2024-07-31 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_courses_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
